theme: jekyll-theme-minimal
title: Nitya Lagadapati
description: Biomaterials | Regenerative Medicine | Machine Learning and Artificial Intelligence
logo: /assets/images/Profile.jpeg
markdown: kramdown
