theme: jekyll-theme-minimal
title: Nitya Lagadapati
description: Biomaterials | Regenerative Medicine | Machine Learning and Artificial Intelligence 
  [LinkedIn](https://www.linkedin.com/in/nitya-lagadapati/) |
  [Resume](/assets/pdfs/Nitya_Lagadapati_Resume.pdf) |
  [CV](/assets/pdfs/Nitya_Lagadapati_CV.pdf)
logo: /assets/images/Profile.jpeg
markdown: kramdown
